apiVersion: v1
kind: Service
metadata:
  name: app-portal-service
  namespace: producao
  labels:
    app: app-portal
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: app-portal
  ports:
  - name: http
    port: 80          # Porta interna do service
    targetPort: 80    # Porta do container
    nodePort: 30080   # Porta externa do cluster
    protocol: TCP
  sessionAffinity: None
